### ISSUE TITLE
Request to use some code

### ISSUE THREAD

**Issue by mandarini** [Myrmod/vitejs-theming#2]
Hi there @Myrmod ! 

I don't see a Licence on your repo, so I wanted to reach out to you to ask if I can use some parts of that replace files for rollup plugin/function you've written. We're building the `vite` plugin for [Nx](https://nx.dev) and I wanted to add the file replacement functionality!

**Comment by Myrmod** [comment]
Of course, go ahead. :)
 
 If it's possible I would be happy if you could include a comment with "Myrmod" in it above. This way I could show my friends. ^^
 
 I'll add an MIT license shortly

**Comment by mandarini** [comment]
Perfect, thanks! :D
